openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /message:
    post:
      tags:
      - rabbit-controller
      operationId: sendMessage
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Message'
        required: true
      responses:
        "201":
          description: Created
components:
  schemas:
    Message:
      type: object
      properties:
        message-content:
          type: string
        message-date:
          type: string
        message-source:
          type: string
